--- !ruby/object:Gem::Specification 
name: kitsune
version: !ruby/object:Gem::Version 
  version: 0.1.2
platform: ruby
authors: 
- Matthew Mongeau <matt@toastyapps.com>
autorequire: 
bindir: bin
cert_chain: []

date: 2010-01-04 00:00:00 -05:00
default_executable: 
dependencies: 
- !ruby/object:Gem::Dependency 
  name: will_paginate
  type: :runtime
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ~>
      - !ruby/object:Gem::Version 
        version: 2.3.11
    version: 
- !ruby/object:Gem::Dependency 
  name: haml
  type: :runtime
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ~>
      - !ruby/object:Gem::Version 
        version: 2.2.12
    version: 
description: Integrated Rails Content Management System.
email: matt@toastyapps.com
executables: []

extensions: []

extra_rdoc_files: []

files: 
- Rakefile
- README.textile
- app/controllers
- app/controllers/admin
- app/controllers/admin/kitsune
- app/controllers/admin/kitsune/application_controller.rb
- app/controllers/admin/kitsune/kitsune_controller.rb
- app/controllers/admin/kitsune/kitsune_users_controller.rb
- app/controllers/admin/kitsune/media_controller.rb
- app/controllers/admin/kitsune/models_controller.rb
- app/controllers/admin/kitsune/pages_controller.rb
- app/controllers/admin/kitsune/records_controller.rb
- app/controllers/admin/kitsune/sessions_controller.rb
- app/controllers/kitsune_controller.rb
- app/helpers
- app/helpers/admin
- app/helpers/admin/kitsune
- app/helpers/admin/kitsune/records_helper.rb
- app/views
- app/views/admin
- app/views/admin/kitsune
- app/views/admin/kitsune/kitsune_users
- app/views/admin/kitsune/kitsune_users/index.html.haml
- app/views/admin/kitsune/kitsune_users/new.html.haml
- app/views/admin/kitsune/media
- app/views/admin/kitsune/media/new.html.erb
- app/views/admin/kitsune/models
- app/views/admin/kitsune/models/index.html.haml
- app/views/admin/kitsune/pages
- app/views/admin/kitsune/pages/_form.html.erb
- app/views/admin/kitsune/pages/edit.html.erb
- app/views/admin/kitsune/pages/index.html.erb
- app/views/admin/kitsune/pages/new.html.erb
- app/views/admin/kitsune/records
- app/views/admin/kitsune/records/_form.html.haml
- app/views/admin/kitsune/records/_list.html.haml
- app/views/admin/kitsune/records/edit.html.haml
- app/views/admin/kitsune/records/index.html.haml
- app/views/admin/kitsune/records/new.html.haml
- app/views/admin/kitsune/sessions
- app/views/admin/kitsune/sessions/new.html.haml
- app/views/admin/kitsune/shared
- app/views/admin/kitsune/shared/_flashes.html.haml
- app/views/kitsune
- app/views/kitsune/show.html.erb
- app/views/layouts
- app/views/layouts/admin
- app/views/layouts/admin/kitsune.html.erb
- config/kitsune_routes.rb
- generators/kitsune
- generators/kitsune/kitsune_generator.rb
- generators/kitsune/lib
- generators/kitsune/lib/insert_commands.rb
- generators/kitsune/templates
- generators/kitsune/templates/images
- generators/kitsune/templates/images/back-arrow.gif
- generators/kitsune/templates/images/bg.jpg
- generators/kitsune/templates/images/box-shadow.png
- generators/kitsune/templates/images/content-bg.gif
- generators/kitsune/templates/images/form-bg.gif
- generators/kitsune/templates/images/grey-btn.png
- generators/kitsune/templates/images/header-bg.gif
- generators/kitsune/templates/images/header-link.png
- generators/kitsune/templates/images/nicEditorIcons.gif
- generators/kitsune/templates/javascripts
- generators/kitsune/templates/javascripts/jquery.js
- generators/kitsune/templates/javascripts/kitsune_jquery.js
- generators/kitsune/templates/javascripts/tiny_mce
- generators/kitsune/templates/javascripts/tiny_mce/langs
- generators/kitsune/templates/javascripts/tiny_mce/langs/en.js
- generators/kitsune/templates/javascripts/tiny_mce/license.txt
- generators/kitsune/templates/javascripts/tiny_mce/plugins
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advhr
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advhr/css
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advhr/css/advhr.css
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advhr/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advhr/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advhr/js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advhr/js/rule.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advhr/langs
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advhr/langs/en_dlg.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advhr/rule.htm
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advimage
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advimage/css
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advimage/css/advimage.css
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advimage/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advimage/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advimage/image.htm
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advimage/img
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advimage/img/sample.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advimage/js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advimage/js/image.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advimage/langs
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advimage/langs/en_dlg.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advlink
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advlink/css
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advlink/css/advlink.css
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advlink/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advlink/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advlink/js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advlink/js/advlink.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advlink/langs
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advlink/langs/en_dlg.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/advlink/link.htm
- generators/kitsune/templates/javascripts/tiny_mce/plugins/autoresize
- generators/kitsune/templates/javascripts/tiny_mce/plugins/autoresize/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/autoresize/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/autosave
- generators/kitsune/templates/javascripts/tiny_mce/plugins/autosave/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/autosave/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/bbcode
- generators/kitsune/templates/javascripts/tiny_mce/plugins/bbcode/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/bbcode/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/contextmenu
- generators/kitsune/templates/javascripts/tiny_mce/plugins/contextmenu/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/contextmenu/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/directionality
- generators/kitsune/templates/javascripts/tiny_mce/plugins/directionality/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/directionality/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/emotions
- generators/kitsune/templates/javascripts/tiny_mce/plugins/emotions/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/emotions/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/emotions/emotions.htm
- generators/kitsune/templates/javascripts/tiny_mce/plugins/emotions/img
- generators/kitsune/templates/javascripts/tiny_mce/plugins/emotions/img/smiley-cool.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/emotions/img/smiley-cry.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/emotions/img/smiley-embarassed.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/emotions/img/smiley-foot-in-mouth.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/emotions/img/smiley-frown.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/emotions/img/smiley-innocent.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/emotions/img/smiley-kiss.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/emotions/img/smiley-laughing.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/emotions/img/smiley-money-mouth.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/emotions/img/smiley-sealed.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/emotions/img/smiley-smile.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/emotions/img/smiley-surprised.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/emotions/img/smiley-tongue-out.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/emotions/img/smiley-undecided.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/emotions/img/smiley-wink.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/emotions/img/smiley-yell.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/emotions/js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/emotions/js/emotions.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/emotions/langs
- generators/kitsune/templates/javascripts/tiny_mce/plugins/emotions/langs/en_dlg.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/example
- generators/kitsune/templates/javascripts/tiny_mce/plugins/example/dialog.htm
- generators/kitsune/templates/javascripts/tiny_mce/plugins/example/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/example/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/example/img
- generators/kitsune/templates/javascripts/tiny_mce/plugins/example/img/example.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/example/js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/example/js/dialog.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/example/langs
- generators/kitsune/templates/javascripts/tiny_mce/plugins/example/langs/en.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/example/langs/en_dlg.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/fullpage
- generators/kitsune/templates/javascripts/tiny_mce/plugins/fullpage/css
- generators/kitsune/templates/javascripts/tiny_mce/plugins/fullpage/css/fullpage.css
- generators/kitsune/templates/javascripts/tiny_mce/plugins/fullpage/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/fullpage/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/fullpage/fullpage.htm
- generators/kitsune/templates/javascripts/tiny_mce/plugins/fullpage/js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/fullpage/js/fullpage.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/fullpage/langs
- generators/kitsune/templates/javascripts/tiny_mce/plugins/fullpage/langs/en_dlg.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/fullscreen
- generators/kitsune/templates/javascripts/tiny_mce/plugins/fullscreen/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/fullscreen/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/fullscreen/fullscreen.htm
- generators/kitsune/templates/javascripts/tiny_mce/plugins/iespell
- generators/kitsune/templates/javascripts/tiny_mce/plugins/iespell/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/iespell/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/inlinepopups
- generators/kitsune/templates/javascripts/tiny_mce/plugins/inlinepopups/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/inlinepopups/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/inlinepopups/skins
- generators/kitsune/templates/javascripts/tiny_mce/plugins/inlinepopups/skins/clearlooks2
- generators/kitsune/templates/javascripts/tiny_mce/plugins/inlinepopups/skins/clearlooks2/img
- generators/kitsune/templates/javascripts/tiny_mce/plugins/inlinepopups/skins/clearlooks2/img/alert.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/inlinepopups/skins/clearlooks2/img/button.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/inlinepopups/skins/clearlooks2/img/buttons.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/inlinepopups/skins/clearlooks2/img/confirm.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/inlinepopups/skins/clearlooks2/img/corners.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/inlinepopups/skins/clearlooks2/img/horizontal.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/inlinepopups/skins/clearlooks2/img/vertical.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/inlinepopups/skins/clearlooks2/window.css
- generators/kitsune/templates/javascripts/tiny_mce/plugins/inlinepopups/template.htm
- generators/kitsune/templates/javascripts/tiny_mce/plugins/insertdatetime
- generators/kitsune/templates/javascripts/tiny_mce/plugins/insertdatetime/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/insertdatetime/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/layer
- generators/kitsune/templates/javascripts/tiny_mce/plugins/layer/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/layer/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/media
- generators/kitsune/templates/javascripts/tiny_mce/plugins/media/css
- generators/kitsune/templates/javascripts/tiny_mce/plugins/media/css/content.css
- generators/kitsune/templates/javascripts/tiny_mce/plugins/media/css/media.css
- generators/kitsune/templates/javascripts/tiny_mce/plugins/media/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/media/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/media/img
- generators/kitsune/templates/javascripts/tiny_mce/plugins/media/img/flash.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/media/img/flv_player.swf
- generators/kitsune/templates/javascripts/tiny_mce/plugins/media/img/quicktime.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/media/img/realmedia.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/media/img/shockwave.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/media/img/trans.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/media/img/windowsmedia.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/media/js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/media/js/embed.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/media/js/media.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/media/langs
- generators/kitsune/templates/javascripts/tiny_mce/plugins/media/langs/en_dlg.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/media/media.htm
- generators/kitsune/templates/javascripts/tiny_mce/plugins/nonbreaking
- generators/kitsune/templates/javascripts/tiny_mce/plugins/nonbreaking/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/nonbreaking/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/noneditable
- generators/kitsune/templates/javascripts/tiny_mce/plugins/noneditable/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/noneditable/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/pagebreak
- generators/kitsune/templates/javascripts/tiny_mce/plugins/pagebreak/css
- generators/kitsune/templates/javascripts/tiny_mce/plugins/pagebreak/css/content.css
- generators/kitsune/templates/javascripts/tiny_mce/plugins/pagebreak/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/pagebreak/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/pagebreak/img
- generators/kitsune/templates/javascripts/tiny_mce/plugins/pagebreak/img/pagebreak.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/pagebreak/img/trans.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/paste
- generators/kitsune/templates/javascripts/tiny_mce/plugins/paste/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/paste/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/paste/js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/paste/js/pastetext.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/paste/js/pasteword.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/paste/langs
- generators/kitsune/templates/javascripts/tiny_mce/plugins/paste/langs/en_dlg.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/paste/pastetext.htm
- generators/kitsune/templates/javascripts/tiny_mce/plugins/paste/pasteword.htm
- generators/kitsune/templates/javascripts/tiny_mce/plugins/preview
- generators/kitsune/templates/javascripts/tiny_mce/plugins/preview/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/preview/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/preview/example.html
- generators/kitsune/templates/javascripts/tiny_mce/plugins/preview/jscripts
- generators/kitsune/templates/javascripts/tiny_mce/plugins/preview/jscripts/embed.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/preview/preview.html
- generators/kitsune/templates/javascripts/tiny_mce/plugins/print
- generators/kitsune/templates/javascripts/tiny_mce/plugins/print/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/print/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/safari
- generators/kitsune/templates/javascripts/tiny_mce/plugins/safari/blank.htm
- generators/kitsune/templates/javascripts/tiny_mce/plugins/safari/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/safari/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/save
- generators/kitsune/templates/javascripts/tiny_mce/plugins/save/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/save/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/searchreplace
- generators/kitsune/templates/javascripts/tiny_mce/plugins/searchreplace/css
- generators/kitsune/templates/javascripts/tiny_mce/plugins/searchreplace/css/searchreplace.css
- generators/kitsune/templates/javascripts/tiny_mce/plugins/searchreplace/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/searchreplace/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/searchreplace/js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/searchreplace/js/searchreplace.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/searchreplace/langs
- generators/kitsune/templates/javascripts/tiny_mce/plugins/searchreplace/langs/en_dlg.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/searchreplace/searchreplace.htm
- generators/kitsune/templates/javascripts/tiny_mce/plugins/spellchecker
- generators/kitsune/templates/javascripts/tiny_mce/plugins/spellchecker/css
- generators/kitsune/templates/javascripts/tiny_mce/plugins/spellchecker/css/content.css
- generators/kitsune/templates/javascripts/tiny_mce/plugins/spellchecker/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/spellchecker/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/spellchecker/img
- generators/kitsune/templates/javascripts/tiny_mce/plugins/spellchecker/img/wline.gif
- generators/kitsune/templates/javascripts/tiny_mce/plugins/style
- generators/kitsune/templates/javascripts/tiny_mce/plugins/style/css
- generators/kitsune/templates/javascripts/tiny_mce/plugins/style/css/props.css
- generators/kitsune/templates/javascripts/tiny_mce/plugins/style/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/style/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/style/js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/style/js/props.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/style/langs
- generators/kitsune/templates/javascripts/tiny_mce/plugins/style/langs/en_dlg.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/style/props.htm
- generators/kitsune/templates/javascripts/tiny_mce/plugins/tabfocus
- generators/kitsune/templates/javascripts/tiny_mce/plugins/tabfocus/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/tabfocus/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/table
- generators/kitsune/templates/javascripts/tiny_mce/plugins/table/cell.htm
- generators/kitsune/templates/javascripts/tiny_mce/plugins/table/css
- generators/kitsune/templates/javascripts/tiny_mce/plugins/table/css/cell.css
- generators/kitsune/templates/javascripts/tiny_mce/plugins/table/css/row.css
- generators/kitsune/templates/javascripts/tiny_mce/plugins/table/css/table.css
- generators/kitsune/templates/javascripts/tiny_mce/plugins/table/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/table/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/table/js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/table/js/cell.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/table/js/merge_cells.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/table/js/row.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/table/js/table.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/table/langs
- generators/kitsune/templates/javascripts/tiny_mce/plugins/table/langs/en_dlg.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/table/merge_cells.htm
- generators/kitsune/templates/javascripts/tiny_mce/plugins/table/row.htm
- generators/kitsune/templates/javascripts/tiny_mce/plugins/table/table.htm
- generators/kitsune/templates/javascripts/tiny_mce/plugins/template
- generators/kitsune/templates/javascripts/tiny_mce/plugins/template/blank.htm
- generators/kitsune/templates/javascripts/tiny_mce/plugins/template/css
- generators/kitsune/templates/javascripts/tiny_mce/plugins/template/css/template.css
- generators/kitsune/templates/javascripts/tiny_mce/plugins/template/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/template/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/template/js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/template/js/template.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/template/langs
- generators/kitsune/templates/javascripts/tiny_mce/plugins/template/langs/en_dlg.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/template/template.htm
- generators/kitsune/templates/javascripts/tiny_mce/plugins/visualchars
- generators/kitsune/templates/javascripts/tiny_mce/plugins/visualchars/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/visualchars/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/wordcount
- generators/kitsune/templates/javascripts/tiny_mce/plugins/wordcount/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/wordcount/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/xhtmlxtras
- generators/kitsune/templates/javascripts/tiny_mce/plugins/xhtmlxtras/abbr.htm
- generators/kitsune/templates/javascripts/tiny_mce/plugins/xhtmlxtras/acronym.htm
- generators/kitsune/templates/javascripts/tiny_mce/plugins/xhtmlxtras/attributes.htm
- generators/kitsune/templates/javascripts/tiny_mce/plugins/xhtmlxtras/cite.htm
- generators/kitsune/templates/javascripts/tiny_mce/plugins/xhtmlxtras/css
- generators/kitsune/templates/javascripts/tiny_mce/plugins/xhtmlxtras/css/attributes.css
- generators/kitsune/templates/javascripts/tiny_mce/plugins/xhtmlxtras/css/popup.css
- generators/kitsune/templates/javascripts/tiny_mce/plugins/xhtmlxtras/del.htm
- generators/kitsune/templates/javascripts/tiny_mce/plugins/xhtmlxtras/editor_plugin.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/xhtmlxtras/editor_plugin_src.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/xhtmlxtras/ins.htm
- generators/kitsune/templates/javascripts/tiny_mce/plugins/xhtmlxtras/js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/xhtmlxtras/js/abbr.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/xhtmlxtras/js/acronym.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/xhtmlxtras/js/attributes.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/xhtmlxtras/js/cite.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/xhtmlxtras/js/del.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/xhtmlxtras/js/element_common.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/xhtmlxtras/js/ins.js
- generators/kitsune/templates/javascripts/tiny_mce/plugins/xhtmlxtras/langs
- generators/kitsune/templates/javascripts/tiny_mce/plugins/xhtmlxtras/langs/en_dlg.js
- generators/kitsune/templates/javascripts/tiny_mce/themes
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/about.htm
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/anchor.htm
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/charmap.htm
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/color_picker.htm
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/editor_template.js
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/editor_template_src.js
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/image.htm
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/img
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/img/colorpicker.jpg
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/img/icons.gif
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/js
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/js/about.js
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/js/anchor.js
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/js/charmap.js
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/js/color_picker.js
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/js/image.js
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/js/link.js
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/js/source_editor.js
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/langs
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/langs/en.js
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/langs/en_dlg.js
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/link.htm
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/skins
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/skins/default
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/skins/default/content.css
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/skins/default/dialog.css
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/skins/default/img
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/skins/default/img/buttons.png
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/skins/default/img/items.gif
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/skins/default/img/menu_arrow.gif
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/skins/default/img/menu_check.gif
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/skins/default/img/progress.gif
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/skins/default/img/tabs.gif
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/skins/default/ui.css
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/skins/o2k7
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/skins/o2k7/content.css
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/skins/o2k7/dialog.css
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/skins/o2k7/img
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/skins/o2k7/img/button_bg.png
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/skins/o2k7/img/button_bg_black.png
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/skins/o2k7/img/button_bg_silver.png
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/skins/o2k7/ui.css
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/skins/o2k7/ui_black.css
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/skins/o2k7/ui_silver.css
- generators/kitsune/templates/javascripts/tiny_mce/themes/advanced/source_editor.htm
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/about.htm
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/anchor.htm
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/charmap.htm
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/color_picker.htm
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/editor_template.js
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/editor_template_src.js
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/image.htm
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/images.json
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/img
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/img/colorpicker.jpg
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/img/icons.gif
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/js
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/js/about.js
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/js/anchor.js
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/js/charmap.js
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/js/color_picker.js
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/js/image.js
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/js/link.js
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/js/source_editor.js
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/langs
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/langs/en.js
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/langs/en_dlg.js
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/link.htm
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/skins
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/skins/default
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/skins/default/content.css
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/skins/default/dialog.css
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/skins/default/img
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/skins/default/img/buttons.png
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/skins/default/img/items.gif
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/skins/default/img/menu_arrow.gif
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/skins/default/img/menu_check.gif
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/skins/default/img/progress.gif
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/skins/default/img/tabs.gif
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/skins/default/ui.css
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/skins/o2k7
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/skins/o2k7/content.css
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/skins/o2k7/dialog.css
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/skins/o2k7/img
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/skins/o2k7/img/button_bg.png
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/skins/o2k7/img/button_bg_black.png
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/skins/o2k7/img/button_bg_silver.png
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/skins/o2k7/ui.css
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/skins/o2k7/ui_black.css
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/skins/o2k7/ui_silver.css
- generators/kitsune/templates/javascripts/tiny_mce/themes/kitsune/source_editor.htm
- generators/kitsune/templates/javascripts/tiny_mce/themes/simple
- generators/kitsune/templates/javascripts/tiny_mce/themes/simple/editor_template.js
- generators/kitsune/templates/javascripts/tiny_mce/themes/simple/editor_template_src.js
- generators/kitsune/templates/javascripts/tiny_mce/themes/simple/img
- generators/kitsune/templates/javascripts/tiny_mce/themes/simple/img/icons.gif
- generators/kitsune/templates/javascripts/tiny_mce/themes/simple/langs
- generators/kitsune/templates/javascripts/tiny_mce/themes/simple/langs/en.js
- generators/kitsune/templates/javascripts/tiny_mce/themes/simple/skins
- generators/kitsune/templates/javascripts/tiny_mce/themes/simple/skins/default
- generators/kitsune/templates/javascripts/tiny_mce/themes/simple/skins/default/content.css
- generators/kitsune/templates/javascripts/tiny_mce/themes/simple/skins/default/ui.css
- generators/kitsune/templates/javascripts/tiny_mce/themes/simple/skins/o2k7
- generators/kitsune/templates/javascripts/tiny_mce/themes/simple/skins/o2k7/content.css
- generators/kitsune/templates/javascripts/tiny_mce/themes/simple/skins/o2k7/img
- generators/kitsune/templates/javascripts/tiny_mce/themes/simple/skins/o2k7/img/button_bg.png
- generators/kitsune/templates/javascripts/tiny_mce/themes/simple/skins/o2k7/ui.css
- generators/kitsune/templates/javascripts/tiny_mce/tiny_mce.js
- generators/kitsune/templates/javascripts/tiny_mce/tiny_mce_popup.js
- generators/kitsune/templates/javascripts/tiny_mce/tiny_mce_src.js
- generators/kitsune/templates/javascripts/tiny_mce/utils
- generators/kitsune/templates/javascripts/tiny_mce/utils/editable_selects.js
- generators/kitsune/templates/javascripts/tiny_mce/utils/form_utils.js
- generators/kitsune/templates/javascripts/tiny_mce/utils/mctabs.js
- generators/kitsune/templates/javascripts/tiny_mce/utils/validate.js
- generators/kitsune/templates/javascripts/upload_maker.js
- generators/kitsune/templates/kitsune_user.rb
- generators/kitsune/templates/migrations
- generators/kitsune/templates/migrations/create_kitsune_users.rb
- generators/kitsune/templates/migrations/create_pages.rb
- generators/kitsune/templates/page.rb
- generators/kitsune/templates/README
- generators/kitsune/templates/stylesheets
- generators/kitsune/templates/stylesheets/global.css
- generators/kitsune/templates/stylesheets/ie.css
- generators/kitsune/templates/VERSIONED_README
- generators/kitsune/USAGE
- generators/kitsune_flat_files
- generators/kitsune_flat_files/kitsune_flat_files_generator.rb
- generators/kitsune_flat_files/templates
- generators/kitsune_flat_files/templates/index.html.erb
- generators/kitsune_flat_files/templates/views
- generators/kitsune_flat_files/templates/views/erb
- generators/kitsune_flat_files/templates/views/erb/admin
- generators/kitsune_flat_files/templates/views/erb/admin/kitsune
- generators/kitsune_flat_files/templates/views/erb/admin/kitsune/models
- generators/kitsune_flat_files/templates/views/erb/admin/kitsune/models/_form.html.erb
- generators/kitsune_flat_files/templates/views/erb/admin/kitsune/models/index.html.erb
- generators/kitsune_flat_files/templates/views/erb/admin/kitsune/pages
- generators/kitsune_flat_files/templates/views/erb/admin/kitsune/pages/_form.html.erb
- generators/kitsune_flat_files/templates/views/erb/admin/kitsune/pages/edit.html.erb
- generators/kitsune_flat_files/templates/views/erb/admin/kitsune/pages/index.html.erb
- generators/kitsune_flat_files/templates/views/erb/admin/kitsune/pages/new.html.erb
- generators/kitsune_flat_files/templates/views/erb/admin/kitsune/records
- generators/kitsune_flat_files/templates/views/erb/admin/kitsune/records/_form.html.erb
- generators/kitsune_flat_files/templates/views/erb/admin/kitsune/records/_list.html.erb
- generators/kitsune_flat_files/templates/views/erb/admin/kitsune/records/edit.html.erb
- generators/kitsune_flat_files/templates/views/erb/admin/kitsune/records/index.html.erb
- generators/kitsune_flat_files/templates/views/erb/admin/kitsune/records/new.html.erb
- generators/kitsune_flat_files/templates/views/erb/kitsune
- generators/kitsune_flat_files/templates/views/erb/kitsune/show.html.erb
- generators/kitsune_flat_files/templates/views/erb/layouts
- generators/kitsune_flat_files/templates/views/erb/layouts/admin
- generators/kitsune_flat_files/templates/views/erb/layouts/admin/kitsune.html.erb
- lib/kitsune
- lib/kitsune/active_record.rb
- lib/kitsune/builder.rb
- lib/kitsune/extensions
- lib/kitsune/extensions/routes.rb
- lib/kitsune/faux_column.rb
- lib/kitsune/form_helper_ext.rb
- lib/kitsune/inspector.rb
- lib/kitsune/mongo_mapper.rb
- lib/kitsune/page.rb
- lib/kitsune.rb
- lib/kitsune_user.rb
- rails/init.rb
has_rdoc: true
homepage: http://github.com/toastyapps/kitsune
licenses: []

post_install_message: 
rdoc_options: []

require_paths: 
- lib
required_ruby_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "0"
  version: 
required_rubygems_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "0"
  version: 
requirements: 
- will_paginate
- haml
rubyforge_project: 
rubygems_version: 1.3.5
signing_key: 
specification_version: 3
summary: Integrated Rails Content Management System.
test_files: []

